name: sentence alignment of cabinet speeches

on:
    push:
        branches:
            -   'master'

jobs:
    SentenceAlignment:
        name: perform sentence alignment
        runs-on:    ubuntu-latest

        steps:
            -   name:   Checkout to develop/master branch
                uses:   actions/checkout@v2

            -   name:   Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: "3.8"

            -   name: Cache pip
                uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                    restore-keys: |
                        ${{ runner.os }}-pip-
                        ${{ runner.os }}-

            
            -   name:   Install python requirements
                run:    |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name:   Install Ubuntu packages
                run:    |
                    sudo apt-get install build-essential
                    sudo apt-get install cmake
                    sudo apt-get install zip

            -   name:   Perform the sentence alignment
                run:    |
                    cd ./src/sentence_alignment/LASER
                    python3 main.py

            -   name:   Commit and push the changes into the repository (master branch) if there are any
                run:    |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    git add .
                    git commit -m "📦(SA): Added new aligned files"
                    git push origin master