name: Sentence Alignment of Cabinet Speeches CI

on:
  workflow_run:
    workflows: [ 'fetch and update cabinent statements' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  SentenceAlignment:
    name: perform sentence alignment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop/master branch
        uses: actions/checkout@v2

      - name: Install Ubuntu packages
        run: |
          sudo apt-get install build-essential
          sudo apt-get install cmake
          sudo apt-get install zip

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"   # Please do not change python version as it will break fairseq dependency
          cache: pip

      #   Installing fairseq using pip version >= 24.1 will BREAK. Please do not change the pip version
      - name: Downgrade pip to 24.0 and install fairseq from GitHub as well as requirements.txt
        run: |
          python -m pip install pip==24.0
          pip install git+https://github.com/facebookresearch/fairseq.git@v0.12.1
          pip install -r requirements.txt

      - name: Perform the sentence alignment
        run: |
          cd src/sentence_alignment
          python main.py

      - name: Show changed files
        run: |
          echo "Changed files:"
          git status
          git diff --name-only

      - name: Show new untracked files
        run: |
          echo "Untracked files:"
          git ls-files --others --exclude-standard

      - name: Commit and push the changes into the repository (master branch) if there are any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📦(SA): Added new aligned files"
