name: Sentence Alignment of Cabinet Speeches CI

on:
    workflow_run:
        workflows: ['fetch and update cabinent statements']
        types:
            - completed
    workflow_dispatch:

jobs:
    SentenceAlignment:
        name: perform sentence alignment
        runs-on:    ubuntu-latest

        steps:
            -   name:   Checkout to develop/master branch
                uses:   actions/checkout@v2

            -   name:   Set up Python
                uses:   actions/setup-python@v4
                with:
                    python-version: "3.12"

            -   name:   Install Fairseq from GitHub
                run: |
                    pip install git+https://github.com/facebookresearch/fairseq.git
            
            -   name:   Install Python requirements
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name:   Install Ubuntu packages
                run: |
                    sudo apt-get install build-essential
                    sudo apt-get install cmake
                    sudo apt-get install zip

            -   name:   Perform the sentence alignment
                run: |
                    python3 ./src/sentence_alignment/main.py

            -   name:   Commit and push the changes into the repository (master branch) if there are any
                uses:   stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: "📦(SA): Added new aligned files"
