name: Sentence Alignment of Cabinet Speeches CI

on:
  workflow_run:
    workflows: [ 'fetch and update cabinet statements' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  SentenceAlignment:
    name: perform sentence alignment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop/master branch
        uses: actions/checkout@v2

      - name: Install Ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake zip

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8   # Please do not change python version as it will break fairseq dependency
          cache: pip

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      #   Installing fairseq using pip version >= 24.1 will BREAK. Please do not change the pip version
      - name: Downgrade pip to 24.0 and install dependencies in requirements.txt
        run: |
          python -m pip install pip==24.0
          pip install -r requirements.txt

      - name: Perform the sentence alignment
        run: |
          cd src/sentence_alignment
          python main.py

      - name: Set datetime of when sentence alignment was completed
        id: alignment_datetime
        run: echo "timestamp=$(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Commit and push the changes into the repository (master branch) if there are any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '📦(SA): Added / updated aligned files on ${{ steps.alignment_datetime.outputs.timestamp }}'
