name: fetch and update cabinent statements

on:
  schedule:
    - cron: '0 14 * * */5' # Every Friday at 2pm
  workflow_dispatch:

jobs:
  fetch_and_update_statements:
    name: fetch and update cabinent statements
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
        
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: execute script
      run: |
        cd src/gov_cab_statements_scrape
        python3 main.py
        cd ../..
    - name: check for repo changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: commit and push if changes
      if: steps.changes.outputs.changed == 1
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Updated govza-cabinet-statements.json on `date` with GitHub Actions"
        git push origin master