name: fetch and update latest cabinent speeches

on:
  schedule:
    - cron: '0 14 * * */5' # Every Friday at 2pm
  workflow_dispatch:

jobs:
  fetch_and_update_latest_speeches:
    name: fetch and update latest cabinent speeches
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute script
        run: |
          cd src/govspeech_scrape
          python3 main.py
      - name: commit and push changes
        run: |
          git add .
          git commit -m "Updated govza-cabinet-statements.json on `date` with GitHub Actions"
          git push origin automate-fetch-update # will switch to master after testing
          